export const PACKAGE_CONSTANTS = {
  faqs: {
    FAQ_HEADING: "Frequently Asked Questions",
  },
  featureComparison: {
    FEATURE_COMPARISON_HEADING: "Feature-by-Feature Comparison",
    FEATURE: "Feature",
    OTT: "OTT",
    STANDARD: "Standard",
    PREMIUM: "Premium",
    ENTERPRISE: "Enterprise",
  },
  packageClarification: {
    PACKAGE_CLARIFICATION_HEADING: "Why This Page Exists — Clarity & Truth",
    YOU_PAY_TITLE: "You pay for:",
    MAIN_TEXT_1: "The first payment you make is",
    MAIN_TEXT_2: "NOT",
    MAIN_TEXT_3: "for leads.",
    DESCRIPTION:
      "It is for building your custom AI qualification engine — QBot — and the entire funnel around it. The qualified leads you receive initially are the output of this system.",
    VALUE_STACK_TITLE: "Value Stack: Every Plan Includes",
    TICK: "✔",
    ENTERPRISE_TEXT: "Enterprise",
    ENTERPRISE_TEXT_2: "includes CRM integration (Bitrix24).",
  },
  packageIntro: {
    PACKAGE_INTRO_HEADING: "4 Powerful Plans, One Outcome",
    QUALIFIED_BUYERS_ONLY: "Qualified Buyers Only.",
    SUB_HEADLINE: "Dual-Verified Leads (Bot + Human) • Zero Junk • Guaranteed First Connect • Lead Replacement",
    COMPARE_PLANS_CTA: "Compare Plans",
    BOOK_10_MINUTE_CTA: "Book 10-Minute QBot Demo",
  },
  packagePrice: {
    PACKAGE_PRICE_HEADING: "Package Comparison",
    PACKAGE_PRICE_SUBHEADING: "Choose the perfect plan for your business needs",
    IDEAL_FOR: "Ideal for:",
    YOU_GET: "You Get:",
    OUTPUT: "Output (Not Charged):",
  },
  packageProcess: {
    HOW_WE_MAKE_LEADS_ZERO_JUNK: "How We Make Leads Zero-Junk",
    EVERY_LEAD_PASSES_THROUGH_TWO_LAYERS: "Every lead passes through two layers:",
    QBOT_QUALIFICATION: "QBot Qualification",
    HUMAN_VERIFICATION: "Human Verification",
    ONLY_AFTER_BOTH_TEXT: "Only after both filters → Lead is considered",
    QUALIFIED_TEXT: '"Qualified."',
    LEAD_REPLACEMENT_GUARANTEE: "Lead Replacement Guarantee",
    IF_A_LEAD_DOES_NOT_PICK_TEXT: "If a lead doesn't pick up 3 attempts",
    WE_REPLACE_IT_TEXT: "We replace it free, No questions asked.",
    DELIVERY_WORKFLOW: "Delivery Workflow",
    ALL_QUALIFIED_LEADS_TEXT: "All qualified leads come with 4 mandatory components:",
    DELIVERED_VIA: "Delivered via:",
    ENTERPRISE_CLIENTS_GET_BITRIX24: "Enterprise clients get Bitrix24.",
    WHY_BUSINESSES_CHOOSE_TEXT: "Why Businesses Choose QLead Over Traditional Marketing",
    YOU_ONLY_PAY_ONCE_TEXT: "You only pay once → for your QBot engine.",
    THE_QUALIFIED_LEADS_TEXT: "The qualified leads that follow come as part of the engine you own.",
    BUILD_YOUR_OWN_LEAD_ENGINE_TEXT: "Build Your Own Lead Engine.",
    STOP_CHASING_START_CLOSING_TEXT: "Stop Chasing. Start Closing.",
    BOOK_YOUR_QBOT_SETUP_CALL_TEXT: "Book Your QBot Setup Call",
    COMPARE_PACKAGES_TEXT: "Compare Packages",
    TALK_TO_GROWTH_EXPERT_TEXT: "Talk to Growth Expert",
  },
};
